name: 'Azure Kubernetes set context'
description: 'Sets the kubeconfig on the machine to communicate with the Azure Kubernetes cluster. Github.com/Azure/Actions'
inputs:
  clientId:
    required: true
    default: ''
  clientSecret:
    required: true
    default: ''
  subscriptionId:
    required: true
    default: ''
  tenantId:
    required: true
    default: ''
  resource-group:
    description: 'Resource Group Name'
    required: false
    default: ''
  cluster-name:
    description: 'AKS Cluster Name'
    required: false
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
